ATTACH 'SQL/L1_forecast_accuracy.duckdb' AS l1;

ALTER TABLE l1.l1_sales DROP COLUMN IF EXISTS store_id;
ALTER TABLE l1.l1_sales DROP COLUMN IF EXISTS item_id;
ALTER TABLE l1.l1_sales DROP COLUMN IF EXISTS id;
ALTER TABLE l1.l1_sales DROP COLUMN IF EXISTS dept_id;
ALTER TABLE l1.l1_sales DROP COLUMN IF EXISTS cat_id;
ALTER TABLE l1.l1_sales DROP COLUMN IF EXISTS state_id;
ALTER TABLE l1.dim_sell_prices DROP COLUMN IF EXISTS store_id;
ALTER TABLE l1.dim_sell_prices DROP COLUMN IF EXISTS item_id;


DETACH DATABASE IF EXISTS l0;
DETACH DATABASE IF EXISTS l1;
DETACH DATABASE IF EXISTS l2;