ATTACH 'SQL/L1_forecast_accuracy.duckdb' AS l1;

ALTER TABLE l1.l1_sales DROP COLUMN store_id;
ALTER TABLE l1.l1_sales DROP COLUMN item_id;
ALTER TABLE l1.l1_sales DROP COLUMN id;
ALTER TABLE l1.l1_sales DROP COLUMN dept_id;
ALTER TABLE l1.l1_sales DROP COLUMN cat_id;
ALTER TABLE l1.l1_sales DROP COLUMN state_id;

DETACH DATABASE IF EXISTS l0;
DETACH DATABASE IF EXISTS l1;
DETACH DATABASE IF EXISTS l2;